### ISSUE TITLE
Source Code for Sequential SVM

### ISSUE THREAD

**Issue by vibhatha** [vibhatha/Parallel_SVM#1]
Source code for SMO and related coding.

**Comment by kyhhdm** [comment]
how about upload your current code? it might be helpful to understand the algorithm by reading them.

**Comment by vibhatha** [comment]
Yes professor, I can upload the current code that I have written. It is the
minified SMO and also I will upload the full version of SMO.

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
Code added.
