### ISSUE TITLE
Second Meeting

### ISSUE THREAD

**Issue by vibhatha** [vibhatha/Parallel_SVM#3]
Discussion on papers.

**Comment by kyhhdm** [comment]
Let's meet next Tuesday 2:00pm-3:00pm, is it ok? 
You two can introduce the papers you read and works have done.
vibhatha 20 minutes
imingtsou 20 minutes
discussion 20 minutes

**Comment by vibhatha** [comment]
Yes professor, it sounds great.

**Comment by kyhhdm** [comment]
Summary of this meeting:
1. set goal of this project in 6 months. 
1). a full svm application integrate into harp. 
2). tech report , if any new ideas found, research paper can be pursued.
2. two directions. 
1). one for smo optimization, long-term task
2). the other for dc-like approach, let's discuss on the dc paper next week

**Comment by vibhatha** [comment]
What is the best way to maintain a tech report ?
Should we use Google docs ?

**Comment by kyhhdm** [comment]
I suggest to use latex to write and then share and sync by using github.

**Comment by imingtsou** [comment]
Well, I prefer tex and use github

**Comment by vibhatha** [comment]
Okay, I will create a Sharelatex project and share it with all team members.

**Comment by kyhhdm** [comment]
I created a project in this repository, Implement DC-SVM. 
Also I added the paper and source code links there, FYI.

**Comment by vibhatha** [comment]
Meeting done.
